apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
  namespace: "{{.Values.PG_NAMESPACE}}"
data:
  APPLICATION_NAME: {{ index .Values "PG_CLUSTER_NAME" }}
  DATABASE: {{ index .Values "PG_DATABASE_NAME" }}