# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  name: helm-charts-template
  tag: latest
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  type: NodePort
  servicePort: 3000
  dns: nodejs-hello-world
  tls: edge
