# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  name: nodejs-hello-world
  tag: "1.1"
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
service:
  type: NodePort
  servicePort: 3000
  dns: apptest
  tls: edge
