# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: nodejs-hello-world
  tag: "1.1"
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 
      memory: 
service:
  type: NodePort
  servicePort: 3000
  dns: nodejs-hello-world
  tls: edge
