kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{  .Chart.Name }}-route"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  host: "{{  .Values.service.dns }}.apps.{{ template "cluster_fqdn" . }}"
  port:
    targetPort: {{ .Values.service.servicePort }}-{{ .Values.service.servicePort }}
  {{- if .Values.service.tls }}
  tls:
    termination: {{ .Values.service.tls }}
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
  {{- end }}
  to:
    kind: Service
    name: "{{  .Chart.Name }}-service"
    weight: 100
      
