kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{  .Chart.Name }}-route"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  host: "{{  .Values.service.dns }}.apps.ocp43-test.sales.lab.tlv.redhat.com"
  to:
    kind: Service
    name: "{{  .Chart.Name }}-service"
    weight: 100
    port:
      targetPort: {{ .Values.service.servicePort }}-{{ .Values.service.servicePort }}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow
      wildcardPolicy: None
      
